### ISSUE TITLE
Can always pick a one-day-range

### ISSUE THREAD

**Issue by henrik-radandt** [wakirin/Lightpick#1]
Hi,

I really like your lib and also use it in production. But there is one thing I don't understand. Even if I set minDays-prop, I am allowed to pick the same day for start and end. I will get a one-day-range. Am I missing something?

Kind regards,
Henrik

**Comment by wakirin** [comment]
Hi @henrik-radandt,

> Am I missing  something?

No, I missed that :)
I'll fix it.
Thanks for information.

**Comment by henrik-radandt** [comment]
Awesome. Works great. Thanks for the fastest fix I ever have seen :-)
