### ISSUE TITLE
Possible locale next/prev button custom text bug?

### ISSUE THREAD

**Issue by harrync** [wakirin/Lightpick#101]
Example - https://codepen.io/TincanPipPip/pen/f42dc4a71fba9dd153c553b721847f38?editors=0010

I'm not sure if this is just because I'm using an SVG as the custom text, but when doing this, only the area around the svg is clickable, the svg element itself isn't so the next/prev month event isn't fired.

Cheers
Harry

**Comment by wakirin** [comment]
Hi,
I guess svg has not been used for these buttons before.
You can add this css, then the whole button will be clickable.

```
button.lightpick__previous-action > svg, 
button.lightpick__next-action > svg {
    pointer-events: none;
}
```

**Comment by harrync** [comment]
Hiya,
Yeah I went a different route (but that's a really good idea), isn't a deal breaker, just wondered if it was a bug or not
Cheers
Harry
