### ISSUE TITLE
Do not show next month

### ISSUE THREAD

**Issue by moseleyi** [wakirin/Lightpick#104]
I have two months next to each other. October and November.

October doesn't have first of November days at the end of the grid but November, as it's the right-most one, has December.

how can I stop it so that the calendar only shows that month?

At the moment I'm doing it with CSS 

```
.is-next-month{display:none;}
```

but it could be a candidate for configuration option, couldn't it?

**Comment by sinankeskin** [comment]
You are doing the right way.

In my opinion, not everything should be an option. That's why css classes exist.
