### ISSUE TITLE
Days grid not displaying properly in IE 11

### ISSUE THREAD

**Issue by brytorres** [wakirin/Lightpick#13]
In IE 11, the grid with for all the day numbers turns into a long vertical list. By adding the -ms-grid prefix, the days are no longer a list but its seems like rows need to be set as well. The `repeat()` notation isn't available in IE.

I added the following:
```
.lightpick__days {
    display: grid;
    display: -ms-grid; // Added this
    grid-template-columns: repeat(7, 1fr);
    -ms-grid-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr; // Added this
}
```

**Comment by Tucsky** [comment]
You might want to switch to flexbox @brytorres 

```
.lightpick__days {
    display: flex;
    flex-wrap: wrap;
}
.lightpick__days > div {
    flex-basis: calc(1 / 7 * 100%);
}
```

**Comment by brytorres** [comment]
@Tucsky That worked great! Thanks!
