### ISSUE TITLE
Configure the months to display

### ISSUE THREAD

**Issue by gajendra93** [wakirin/Lightpick#14]
I need to configure the months that I display. For eg. current month and last month. How can we do that?

**Comment by wakirin** [comment]
Months in the calendar so far shown only in order

**Comment by gajendra93** [comment]
I know that's in order, but if we need to show last month and current month, how to configure that?

**Comment by wakirin** [comment]
You can't do it at this moment. I said "so far shown **only** in order".

**Comment by venky3989** [comment]
public class AdfFileDAO extends DaoBase  {
	File rootDirectory = null;

	public AdfFileDAO(File rootDirectory) {
		if (!rootDirectory.exists()) {
			throw new IllegalArgumentException("Directory " + rootDirectory.getAbsolutePath() + " doesn't exist");
		}
		this.rootDirectory = rootDirectory;
	}
	// Here Directory name will appear
	protected ITreeNode readRoot(ITree tree) {
		tree.setRoot(readNode(this.rootDirectory));
		//System.out.println("readRoot...."+tree.getRoot());
		return tree.getRoot();
	}

	
	protected Set<ITreeNode> readChildren(ITreeNode parentNode) {
		System.out.println("readChildren parentNode........"+parentNode);
		Set<ITreeNode> children = new HashSet<ITreeNode>();
		File parentDir = (File) parentNode.getObject();
		String[] files = parentDir.list();
		if (files == null)
			return children;
		for (int i = 0; i < files.length; i++) {
			File childFile = new File(parentDir.getAbsolutePath() + File.separator + files[i]);
			ITreeNode child = readNode(childFile);
			child.setParentId(parentNode.getId());
			//System.out.println("child....."+child);
			if (!childFile.exists())
				continue;
			children.add(child);
		//	System.out.println("children......."+children);
		}
		return children;
	}

	protected Set<ITreeNode> readGrandChildren(ITreeNode parentNode) {
		System.out.println("parentNode......."+parentNode); 
		Set<ITreeNode> grandChildren = new LinkedHashSet<ITreeNode>();
		Iterator<ITreeNode> children = parentNode.getChildren().iterator();
		System.out.println("children......."+children);
		while (children.hasNext()) {
			ITreeNode child = children.next();
		//	System.out.println("child ....."+child);
			grandChildren.addAll(readChildren(child));
		}
		System.out.println("grandChildren......."+grandChildren);
		//TreeSorter.sortById(parentNode);
		return grandChildren;
	}

	protected ITreeNode readNode(File file) {
		if (!file.exists())
			return null;
		ITreeNode node = null;
		String childType = file.isDirectory() ? "directory" : "file";
		if (childType.equals("file")) {
			node = new TreeNode(file.getAbsolutePath(), "<a href=\"openPdf.jsp?fileName=" + file.getAbsolutePath() + "\" target=_blank>" + file.getName() + "</a>", childType);
		} else {
			node = new TreeNode(file.getAbsolutePath(), file.getName(), childType);
		}
		node.setObject(file);
		return node;
	}

}
(https://github.com/business-logic/br4j/blob/master/base/SharedComponents/Controls/src/com/jenkov/prizetags/tree/impl/FileDao2.java)
In this above code i have used my project to displying the Calendar months. while developing this so here am getting one issue at readGrandChildren() method. just go through the above link.
like here am getting calendar months ascending order but i want to display calendar order means Jan,Feb,Mar.....Dec.

Thanks&Regards,
Venkat.
