### ISSUE TITLE
Bug: On select method invoked when Lightpick instance is created

### ISSUE THREAD

**Issue by rsdebest** [wakirin/Lightpick#15]
Line 710 of lightpick.js causes several bugs in our implementation when reinitializing because the bound onSelect function is being called immediately. Is there a specific reason why this is done or is this line of code redundant?   

`710: opts.onSelect.call(this, this.getStartDate(), this.getEndDate());`

**Comment by wakirin** [comment]
You are right, it's redundant code. Thanks.
