### ISSUE TITLE
Separate style for days that specify in disableDates field

### ISSUE THREAD

**Issue by shuramita** [wakirin/Lightpick#17]
When disabledDates option was set, Lightpick render the date that same style as normal disabled date like min date and max date
It should be different for identify
In attached image,
The date from 29 to Aug to 6 Sept and 26 sept to 30 sept are set in disabledDates

![image](https://user-images.githubusercontent.com/2621362/45194407-1521e880-b27d-11e8-9177-413f8d8f2e2e.png)

**Comment by wakirin** [comment]
You can do something like this https://jsfiddle.net/q8n17ydk/18/

It's new option `tooltipOnDisabled` in `locale` (not documented yet).
Better use with option `selectForward`.
