### ISSUE TITLE
Display issue with VueJS

### ISSUE THREAD

**Issue by periode** [wakirin/Lightpick#18]
Hello!

I've tried to use Lightpick with a Vue application, and even though it does display, the CSS isn't correct at all.....

<img width="900" alt="screen shot 2018-09-21 at 8 41 36 pm" src="https://user-images.githubusercontent.com/1785254/45900051-de041900-bdde-11e8-9ecc-cc417a01e2a3.png">

Here is the code I have:
```
const Lightpick = require('lightpick')

let picker_availability = new Lightpick({
  field: document.getElementById("pick-availability"), //this is a <input type="text"/> element
  onSelect: function(date){
        console.log(date);
  },
  numberOfColumns: 3,
  singleDate: false
})
```

I've disabled any external CSS I might have, so I think it might actually be a problem with Lightpick's CSS itself?

**Comment by wakirin** [comment]
Hello,
did you include css styles ? 
```
@import "~lightpick/css/lightpick.css";
```

**Comment by periode** [comment]
Haha, no I didn't that fixed it, thanks!
