### ISSUE TITLE
IE Compatibility

### ISSUE THREAD

**Issue by linushoremans** [wakirin/Lightpick#25]
Object.assign is not working in IE, throwing errors.
(Fixed with js polyfill)

Grid not compatible in IE11. Tried using polyfill for the css but no success so far.

**Comment by wakirin** [comment]
You need to use v1.0.9 or lower, in v1.1.0 support IE has dropped (see [CHANGELOG.md](https://github.com/wakirin/Lightpick/blob/master/CHANGELOG.md)).

**Comment by linushoremans** [comment]
Thanks!

**Comment by animald** [comment]
What was your reasoning for switching to css grid out of interest?
