### ISSUE TITLE
configure the display of days to sun-mon-tues-wed-thu-fri-sat format

### ISSUE THREAD

**Issue by lawrenzhoo** [wakirin/Lightpick#26]
does configuring the display of days in the calendar from mon-tue-wed-thu-fri-sat-sun to sun-mon-tue-wed-thu-fri-sat format is possible?

**Comment by wakirin** [comment]
try to set [firstDay](https://github.com/wakirin/Lightpick#firstday) to 7

**Comment by lawrenzhoo** [comment]
Great it works! Thanks a lot.
