### ISSUE TITLE
input values on range is not set as default dates

### ISSUE THREAD

**Issue by eusonlito** [wakirin/Lightpick#28]
Having two inputs for date range:

```html
<input type="text" value="01-01-2019" name="start_at" id="form-setup-start_at" />
<input type="text" value="31-01-2019" name="end_at" id="form-setup-end_at" />
```
```js
new Lightpick({
    format: 'DD-MM-YYYY',
    field: document.getElementById('form-setup-start_at'),
    secondField: document.getElementById('form-setup-end_at'),
    singleDate: false
});
```

The start and end date is not set on calendar, and input values are set to empty.

How I can configure calendar to load default dates from input values?

Thanks!

**Comment by wakirin** [comment]
Hello,
I'll try check this issues on this week.
Thanks for report.

**Comment by eusonlito** [comment]
Working! Thanks!

**Comment by wakirin** [comment]
Cool, this changes will be include in 1.2.9 version.
