### ISSUE TITLE
night counting, it only count days i want to count Nights

### ISSUE THREAD

**Issue by milandulals** [wakirin/Lightpick#32]
For days it shows 2 days but its one night, if I wanna change the value just by -1 on tooltip how can i

**Comment by milandulals** [comment]
**light pick.js line no 697 correction to 0 works with adding 

tooltip: {
one : 'night',
other: 'nights',
}
**

**Comment by wakirin** [comment]
@milandulals  did you check option [tooltipNights](https://github.com/wakirin/Lightpick#tooltipnights) ?
