### ISSUE TITLE
Disable auto jump to next month

### ISSUE THREAD

**Issue by hihahihahoho** [wakirin/Lightpick#35]
How can i disable auto jump to current selected month when i select range?
When i select range and open it again, the month automatically jump to first.
![image](https://user-images.githubusercontent.com/29968144/52110206-800bfb80-2632-11e9-8574-5c7920660c18.png)

**Comment by wakirin** [comment]
There is no options for control it. 
But you can do something like this https://jsfiddle.net/waki/9gym87L4/6/

**Comment by hihahihahoho** [comment]
Thanks!
