### ISSUE TITLE
False to sync date on picker with date on input box when select date range

### ISSUE THREAD

**Issue by hihahihahoho** [wakirin/Lightpick#36]
The picker doesn't sync the dates when i modify input box
it's automatically sync in select single date mode
![image](https://user-images.githubusercontent.com/29968144/52162127-de53df80-2701-11e9-9a70-60ec14166757.png)

**Comment by wakirin** [comment]
Sorry don't have enough time for it at this moment, I'll try to check it on next week.

**Comment by wakirin** [comment]
@hihahihahoho please check latest version (1.2.10).

**Comment by hihahihahoho** [comment]
> @hihahihahoho please check latest version (1.2.10).

The end date is not fixed yet in single input box mode
![image](https://user-images.githubusercontent.com/29968144/52692524-b16fba00-2f96-11e9-80c3-d783104dad1d.png)

**Comment by wakirin** [comment]
You are right, I has fix it in 1.2.11
