### ISSUE TITLE
disable all dates that has been passed

### ISSUE THREAD

**Issue by lawrenzhoo** [wakirin/Lightpick#40]
Is there anyway to disable the days that has been passed? or disable the dates less than today?

**Comment by wakirin** [comment]
use option [minDate](https://github.com/wakirin/Lightpick#mindate)

**Comment by lawrenzhoo** [comment]
I'm sorry but I don't know how to use minDate, i've read the documentary but I still don't have any idea on how to use it. 

ive tried this but doesn't work

var picker = new Lightpick({
			
	var today = new Date();

	minDate: today,
	disableWeekends: true,
	field: document.getElementById('lightpick-datepicker'),

});

**Comment by wakirin** [comment]
Why you trying init `today` inside Lightpick ?
For your case you can do it:
```
var picker = new Lightpick({
    field: document.getElementById('lightpick-datepicker'),
    minDate: new Date(),
    disableWeekends: true
});
```

**Comment by lawrenzhoo** [comment]
ohhh so that's how its done, I thought i need to declare a new variable and put it in on the minDate my bad hahahaha.
