### ISSUE TITLE
Check availability of the dates

### ISSUE THREAD

**Issue by lawrenzhoo** [wakirin/Lightpick#41]
Does this plugin have the ability to Check Availability of the dates?

I'm borrowing/using your plugin to my simple project. My project is booking a tour, I need to check the availability of the dates in by color coding if the dates is full or not and how many slots available does a certain date have left.

**Comment by wakirin** [comment]
Lightpick can't check, you must check availability of dates by yourself and mark unavailable dates with method [setDisableDates](https://github.com/wakirin/Lightpick#pickersetdisabledatesarray).
It's can looks something like that:
```
let picker = new Lightpick({
    field: document.getElementById('lightpick-datepicker'),
    minDate: new Date(),
    disableWeekends: true
});

let disabledDates = // here ajax request to your API for fetch unavailable dates as array. 
// for example API has returned that array: 
// [
//    ['2019-02-05', '2019-02-11'],
//    ['2019-02-14', '2019-02-16']
// ]

// set to picker unavailable dates
picker.setDisableDates(disabledDates);
```

**Comment by lawrenzhoo** [comment]
Ohh great ill go with that, thanks! Is it possible too to change the color of it? or ill that myself too? or not doable?

**Comment by wakirin** [comment]
You can customize style by yourself, for first include css styles of lightpick, then include your custom style.

**Comment by lawrenzhoo** [comment]
I tried this code but still doesn't work. 

JS code: 

		let disabledDates = $.ajax({
			method: "POST",
			url: "fetch.php",
			data: {data:data},
			dataType: "json"
		}).done(function(response){  
		   console.log(response);
		})

		picker.setDisableDates(disabledDates);  

PHP Script: 


	if(isset($_POST['data'])) {
		
		$tour_id = "TOUR5c5dae60ef75b";
		$sched = "02/23/2019";
		
		$sql = "SELECT bookings.tour_id,
					 bookings.package_id,
					 bookings.booking_id,
					 bookings.date_scheduled,
					 packages.package_id,
					 packages.tour_id,SUM(packages.package_pax) as total_slot 
			  FROM bookings 
			  LEFT JOIN packages 
			  ON bookings.package_id=packages.package_id 
			  WHERE bookings.date_scheduled='$sched' and 
					bookings.tour_id='$tour_id' and 
					packages.tour_id='$tour_id'";
					
		$sql_2 = "SELECT * FROM bookings WHERE tour_id='$tour_id' GROUP BY date_scheduled";
					
		$res = mysqli_query($conn,$res) or die("Error unable to fetch data: " . mysqli_error($conn));
		
		$output = "";
		
		while($row = mysqli_fetch_assoc($res))	{
			$output .= $row['date_scheduled'];
		}
		
		$data = array($output);
		echo json_encode($data);
		
    }

**Comment by wakirin** [comment]
`$.ajax` send async request, you must use `picker.setDisableDates` in `done` callback.
I has prepared example without jquery https://jsfiddle.net/waki/bot3xL7g/9/

**Comment by lawrenzhoo** [comment]
Ohh thats perfect, I just to have a php script returns a value like this https://dev.lvl.ninja/lightpick/

But isn't this range date picker? how can I disable a single different dates?
