### ISSUE TITLE
Very slow rendering when set large array of disableDate

### ISSUE THREAD

**Issue by kekatxxx** [wakirin/Lightpick#42]
Hi,
thanks for the excelent work. I found that when you pass a large array of disableDates (like 100 days) the rendering is very slow (when the page is loaded and when you change month).
Regards, Francesco

**Comment by wakirin** [comment]
Hi,
can you please provide on jsfiddle your case ?

I've check with array of 200 days and doesn't see «very slow rendering»
https://jsfiddle.net/waki/bf4xpkmz/4/

**Comment by kekatxxx** [comment]
Thanks,
is not very slow but a little bit. Thnks anyway.
In adiction I noted that on the mobile the arrows doesn't work wery well.
Did you notice it?
Thanks

Il giorno mer 20 feb 2019 alle ore 05:14 waki <notifications@github.com> ha
scritto:

**Comment by kekatxxx** [comment]
*In adiction I noted that on the mobile the arrows doesn't work wery well.
Did you notice it? *
Sorry there was a CSS error, please ignore this note.

Il giorno mar 5 mar 2019 alle ore 17:08 Francesco Barbieri <
checcobarbieri@gmail.com> ha scritto:
