### ISSUE TITLE
Render calendar as an inline component

### ISSUE THREAD

**Issue by ngmikeng** [wakirin/Lightpick#43]
I curious to know is there an official way to render or init the calendar inline without a input element.
As you can see currently the input's click event is triggered when first load page and I set `hideOnBodyClick` and `autoclose` equal false to making the calendar inline.
https://codepen.io/ngmikeng/pen/LqKVdV

Thanks for great work.

**Comment by wakirin** [comment]
At this moment doesn't have that option, but I see it's useful option, I'll add it later. (After another issues, there is have another ideas (see another issues), but now don't have time for it).

**Comment by ngmikeng** [comment]
Take your time @wakirin.

**Comment by wakirin** [comment]
@ngmikeng check latest version (1.3.1), there added option `inline`.

**Comment by ngmikeng** [comment]
Awesome, thank you @wakirin.
