### ISSUE TITLE
Input value not using the language

### ISSUE THREAD

**Issue by gabspisa86** [wakirin/Lightpick#44]
Hi,
I set IT language in the component, but, after the selction of the range, the input's value is EN like in the picture:
![bug](https://user-images.githubusercontent.com/12732189/53574082-26ceb380-3b6f-11e9-8c12-574b3fcddefd.PNG)

I have fixed by adding this method [moment.locale(opts.lang);] at line 886 in the lightpick.js, after the set of 'opts.lang'.

The result is the following:
![solution](https://user-images.githubusercontent.com/12732189/53574437-e885c400-3b6f-11e9-8303-d0d4f9335d49.PNG)

Regards, Gabriele.

**Comment by wakirin** [comment]
Hello,
you can control output text in `onSelect` callback function.
