### ISSUE TITLE
is-start-date class not cleaned on newly selected date

### ISSUE THREAD

**Issue by dennisexozet** [wakirin/Lightpick#47]
Hi,

unfortunately there seems to be a problem when using Lightpick with options autoclose = false, singleDate = true (and hiddenOnBodyClick= false).

I tried to use the Lightpick as some kind of calendar and the problem I face is that when selecting a new date (e.g. I clicked a wrong date before) the previously selected fields still have the 'is-start-date' class. There's no cleaning of previously set classes on old fields.

Is there a chance that you'll fix this?

Thanks in advance,
Dennis

**Comment by wakirin** [comment]
Hi,
Today I fixed issue https://github.com/wakirin/Lightpick/issues/43 and now I guess latest changes is cover your problem. 
Please check new example with option `inline`: https://wakirin.github.io/Lightpick/

**Comment by dennisexozet** [comment]
Hi,

thanks so far. It works like expected.

You can close this issue.
