### ISSUE TITLE
Error when `inline = true` and `field = null`

### ISSUE THREAD

**Issue by gilles-crealp** [wakirin/Lightpick#50]
Has you can see [here](https://jsfiddle.net/GilMar_CREALP/y6tapeL7/), Lightpick return the following error: `TypeError: Cannot read property 'value' of null` when `inline = true` and `field = null`.

Related to #43.

**Comment by wakirin** [comment]
`field` can't be null, see example https://wakirin.github.io/Lightpick/ (there input element is hide by inline style `display: none`)

**Comment by gilles-crealp** [comment]
OK
