### ISSUE TITLE
toggle the calendar on button click

### ISSUE THREAD

**Issue by futwick** [wakirin/Lightpick#62]
Instead of a text input, I have used a button as my Lightpick element.

https://jsfiddle.net/swcg6jmz/1/

It works very well - the calendar is shown when the button is clicked - but it would be even better if there was a way to toggle the calendar so that it is hidden when the button is clicked a second time.

**Comment by sinankeskin** [comment]
Hi.
I see what you mean but I guess it's a little bit odd for a11y.

How about **autoclose=false** and click **X** button to close action?

I think this way is better.

I'm closing feel free to reopen if you need any other help.

Thank you.
