### ISSUE TITLE
Ability to clear the selected date

### ISSUE THREAD

**Issue by rsmything** [wakirin/Lightpick#66]
It would be very nice to have the opportunity to clear the previously selected date in the calendar (clean the value from field)

Just add a cross somewhere or a button neatly

![Снимок экрана 2019-04-28 в 11 17 43](https://user-images.githubusercontent.com/11719983/56859657-69faa680-69a7-11e9-8abf-fe7c7d5259b8.png)

**Comment by rsmything** [comment]
Found reset option, but it would be better if the reset button clears and closes the calendar window

**Comment by animald** [comment]
You could create your own reset button which calls the reset() and hide() methods.

**Comment by sinankeskin** [comment]
As @animald states you can call reset() and hide() to do that.

I'm closing. If you need any other assistance feel free to reopen.

Thank you.
