### ISSUE TITLE
please consider providing CDN support

### ISSUE THREAD

**Issue by lingtalfi** [wakirin/Lightpick#69]
Hi, did you consider putting lightpick on CDN (https://cdnjs.com/ for instance)?

That would be great.

**Comment by sinankeskin** [comment]
Nice suggestion but unfortunatly looks like this library doesn't met cdnjs [requirements](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library)

Cdnjs requires minimum 200 stars on GitHub.

Thank you.

**Comment by jeffkarney** [comment]
It looks like https://www.jsdelivr.com/ willl serve up any GitHub repo. You can simply use... https://cdn.jsdelivr.net/gh/wakirin/Lightpick@v1.3.2/lightpick.js and https://cdn.jsdelivr.net/gh/wakirin/Lightpick@v1.3.2/css/lightpick.css

**Comment by sinankeskin** [comment]
Hey Jeff. Thank you for the info.

I didn't know that. This is invaluable.

Also looks like [unpkg](https://unpkg.com/) does the same thing from npm.

I'm closing the issue. Feel free to reopen if you need anything.
