### ISSUE TITLE
Update dates when footer=true inline=false and autoclose=false

### ISSUE THREAD

**Issue by Undique** [wakirin/Lightpick#74]
Hi, when i use these options footer=true, inline=false and autoclose=false
highlighted day cannot be updated, because there are no condition check for that. As a result i can select (visually) all of the days before submit.

**Comment by sinankeskin** [comment]
Hi.

Do you mean all of days showing as selected? At least I'm seeing this.

Thank you.

**Comment by Undique** [comment]
when any date is clicked "is-start-date" class is added
although all previous elements which already has this class doesn't update
as a result we have many selected days
I've added fiddle to reproduce this behaviour:
https://jsfiddle.net/NDQ/c1ednmkz/

**Comment by Undique** [comment]
I believe its for the missing ifelse condition on line 576
```
else if (!opts.singleDate || opts.inline) {
    updateDates(self.el, opts);
}
```

I've updated this block this way:
```
else if (!opts.singleDate || opts.inline || (opts.footer && !opts.autoclose)) {
    updateDates(self.el, opts);
}
```

**Comment by sinankeskin** [comment]
You were right.

Check for autoclose is suffice. Fixed now.

Thank you.
