### ISSUE TITLE
Tooltip definition doesn't appear to be working

### ISSUE THREAD

**Issue by digitalredefned** [wakirin/Lightpick#79]
Noticed this on a site I'm working on and I verified this issue with the demo code.   When attempting to change the tooltip values, the new values are not being recognized on latest version.

// demo-3
new Lightpick({
    field: document.getElementById('demo-3_1'),
    secondField: document.getElementById('demo-3_2'),
    tooltipNights: true,
    tooltip: {
        one: 'night',
        other: 'nights'
    },
    onSelect: function(start, end){
        document.getElementById('result-3').innerHTML = rangeText(start, end);
    }
});

**Comment by sinankeskin** [comment]
Hi Jim.

By convention you should add singleDate = false to your options manually. If you leave blank this parameter assigned as true. Tooltips only shown when this parameter is false.

I'm closing this issue.

Feel free to reopen if you need any other help.

Thanks.
