### ISSUE TITLE
Multiple select date

### ISSUE THREAD

**Issue by arhakim** [wakirin/Lightpick#86]
Hi,

Is it possible to activate/select multiple dates? especially when in inline mode.

Thanks for this great datepicker!

**Comment by sinankeskin** [comment]
Hi Andri.

Yes you can select multiple dates with singleDate parameters. If you give false to this parameter it'll show 2 dates selected in input.

I'm closing. Feel free the issue if you need any other help.

Thanks.

**Comment by arhakim** [comment]
@sinankeskin Thanks for the answer.
But what I want to do is, how to select multiple dates like this:
 2019-10-21, 2019-10-23, 2019-10-25

![Screenshot_65](https://user-images.githubusercontent.com/5907138/67449127-4a38f800-f643-11e9-8b2f-8d60c2dad95f.png)

**Comment by sinankeskin** [comment]
As of now, you can't do this with Lightpick.

This feature requested a couple of times.
Maybe later.

Thanks.
