### ISSUE TITLE
 Lightpick  IE 11 support issue

### ISSUE THREAD

**Issue by mayjoy20** [wakirin/Lightpick#88]
Hi,
I tried to download lightpick older version for IE 11  version 1.0.9 but i couldn't find a source for that please give a lin to download. or else how can i solve the date picker issue in IE 11.
Days grid not displaying properly in IE 11
I saw this 

.lightpick__days {
    display: grid;
    display: -ms-grid; // Added this
    grid-template-columns: repeat(7, 1fr);
    -ms-grid-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr; // Added this
}

but where to add this code 
in demo.js or lightpick.js
please extend your helping hand on this issue

**Comment by sinankeskin** [comment]
After the load lightpick.css, you can add this style wherever you want. Inline or another css file. It doesn't matter.

Same selectors will be overridden automatically.
