### ISSUE TITLE
Day of the week format

### ISSUE THREAD

**Issue by harrync** [wakirin/Lightpick#91]
Hiya,
Firstly, great plugin, thanks so much!

I was wondering whether it's possible to change the day of the week format, e.g. instead of 'Mon Tues etc' it's 'M T etc'?

Many thanks

**Comment by sinankeskin** [comment]
Hi Harry.
I've just added as a collaborator and thanks for the suggestion.
Looks like this is [possible](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) but original author thought this parameter only can have 2 values (short, long). Therefore this parameter is a boolean.

We'll think about the third value.

Thanks.

**Comment by harrync** [comment]
Thanks for the quick reply chap, hugely appreciated!

**Comment by sinankeskin** [comment]
You're welcome. I don't have permission to publish on npm. Whenever the author gives I'll publish on npm also.
