### ISSUE TITLE
Multiple days select 

### ISSUE THREAD

**Issue by Barmadzilla** [wakirin/Lightpick#93]
Hi guys.
This picker is awesome and flexible for setup. I like it.
Could you add 'multiple days select' feature. It will be great.

Best regards.

**Comment by sinankeskin** [comment]
Hi Valery.

If you pass singleDate parameter to false. You can select 2 days. Start and End days.

What do you mean by multiple days? More than 2 days?

Thank you.

**Comment by Barmadzilla** [comment]
Yes. But i need select 2 or 4 different dates in single field. For example 20.10, 22.10 ,03.11 and etc. Multiple days in different order. Not in a row.

**Comment by sinankeskin** [comment]
At this moment this project doesn't support more than two days.

Maybe in the future @wakirin will implement this.

Now I'm closing this issue. Feel free to contact any other assistance.

Thanks for the suggestion.
